//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMenu
    {
        public tblMenu()
        {
            this.tblMenuItems = new HashSet<tblMenuItem>();
        }
    
        public long MenuID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<bool> Published { get; set; }
        public Nullable<bool> Locked { get; set; }
    
        public virtual ICollection<tblMenuItem> tblMenuItems { get; set; }
    }
}
