//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProviderMenuItem
    {
        public tblProviderMenuItem()
        {
            this.tblMenuItems = new HashSet<tblMenuItem>();
        }
    
        public long ProviderMenuItemID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> MenuItemTypeID { get; set; }
        public int LikeCount { get; set; }
        public int DislikeCount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual ICollection<tblMenuItem> tblMenuItems { get; set; }
        public virtual tblMenuItemType tblMenuItemType { get; set; }
    }
}
