//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblUser
    {
        public tblUser()
        {
            this.tblUserMenus = new HashSet<tblUserMenu>();
            this.tblTokens = new HashSet<tblToken>();
        }
    [Key]
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> LastLoginDateTime { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<tblUserMenu> tblUserMenus { get; set; }
        public virtual ICollection<tblToken> tblTokens { get; set; }
    }
}
